"""update blacklist table

Revision ID: d32f9f75aa33
Revises: 34fc3fd79a22
Create Date: 2026-03-05 14:38:14.555539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32f9f75aa33'
down_revision: Union[str, Sequence[str], None] = '34fc3fd79a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_blacklist', sa.Column('token_type', sa.String(), nullable=False))
    op.add_column('token_blacklist', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_column('token_blacklist', 'created_at')
    op.drop_column('token_blacklist', 'token_type')
    # ### end Alembic commands ###
